### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by ccf5maj37** [projectdiscovery/rawhttp#214]
https://github.com/projectdiscovery/rawhttp/commit/aeaed825ad3c1148b25213948c879f0a97c055c1
https://github.com/projectdiscovery/rawhttp/blame/main/proxy/http.go#L36
The commit above will cause a coroutine/memory leak. After calling the fastdialer library, the dialer is not closed, which will result in the coroutines related to the leveldb opened by it not being able to exit normally.
This issue will lead to memory leaks in nuclei when proxies are used.

**Comment by ehsandeep** [comment]
More context: https://github.com/projectdiscovery/nuclei/discussions/4374#discussioncomment-7584534
